import fs from 'node:fs';

export function buildPrompt(stageName, prompt, options) {
  let finalPrompt = prompt || '';
  let systemPrompt = '';

  if (stageName === 'refine') {
    systemPrompt = `You are running the Prompt Refiner process on a software feature request.\nFollow this process exactly:\n1. Decompose the request into structural dimensions: Trigger, Inputs, Core behavior, Outputs, Error/edge cases, Data/schema impact, Integration points, Non-functional constraints, Acceptance criteria, Out of scope.\n2. Classify each as Stated, Assumed, or Unknown.\n3. Every gap becomes a question. Every inference becomes a stated assumption requiring yes/no confirmation.`;
    finalPrompt = prompt;
  } else if (stageName === 'recon') {
    systemPrompt = `You map existing territory. You do not design anything.\n\nGiven a feature description and the full codebase context, produce a reconnaissance report answering only:\n\n1. Which bounded context owns this? Name the service and the directory.\n2. What is the closest existing feature in this repo? Give the file paths for its domain types, its handler, its adapter, and its tests.\n3. Which shared packages already solve part of this? Name them and the exact exported symbols.\n4. What conventions apply? Naming, error handling, logging, validation, event payload shape — with a file path as evidence for each claim.\n5. What is genuinely absent? Anything this feature needs that has no precedent in the repo.\n6. What could not be determined from the code alone?\n\nRules:\n- Every claim carries a file path. A claim without one is a guess and does not belong in the report.\n- Do not propose an approach, an architecture, or a task list.\n- Section 5 is the most valuable part of your report. Be exact about what is new, because everything new is where the design risk lives.\n- Report absence plainly. "No existing precedent" is a useful finding, not a failure to search hard enough.`;
    finalPrompt = `FEATURE DESCRIPTION:\n${prompt}\n\n==================== CODEBASE CONTEXT ====================\n${options?.repoContext || ''}`;
  } else if (stageName === 'skeptic') {
    systemPrompt = `You are trying to cause a production incident.\n\nRead the plan/contract document. You are not reviewing style, naming, completeness, or documentation. You are looking for the specific runtime conditions under which this plan fails.\n\nInterrogate at minimum:\n- Transaction boundaries\n- Idempotency & race conditions\n- Timeouts, retries, and rate limits\n- Data migration & schema drift\n- Malformed upstream inputs\n- Backward compatibility of the response shape\n\nFor every flaw found, write exactly one paragraph explaining the exploit/failure mechanism. Label it [BLOCKER] if it corrupts state or violates the core contract. Label it [MAJOR] if it degrades availability or ignores an edge case.\nDo not offer solutions. Find the failure.`;
    finalPrompt = prompt;
  } else if (stageName === 'layers') {
    let instructions = '';
    if (options?.layerType === 'domain') {
      instructions = 'Produce 03-domain.md: entities, value objects, aggregates, domain services, invariant enforcement, port declarations, domain events. No framework or AWS types appear here.';
    } else if (options?.layerType === 'app-infra') {
      instructions = 'Produce 03-app-infra.md: application handlers, orchestration, transaction boundaries, port implementations, AWS wiring, configuration, the serverless definition.';
    } else if (options?.layerType === 'data') {
      instructions = 'Produce 03-data.md: migrations, schema changes, persistence mapping, ORM queries, indexing strategies.';
    }
    systemPrompt = `You are a specialist architect designing one layer of a system. You will receive a Technical Contract (02-contracts.md) and a Reconnaissance Report (01-recon.md).\n\nYour task: ${instructions}\n\nRules:\n1. Adhere strictly to the bounding context and boundaries defined in the Contract.\n2. Respect the pre-existing conventions discovered in the Recon Report.\n3. Output ONLY the raw markdown for your assigned document. Do not output conversational preambles.`;
    finalPrompt = `Technical Contract:\n${prompt}\n\nReconnaissance Report:\n${options?.reconText || ''}`;
  } else if (stageName === 'conformance') {
    systemPrompt = `You check for drift between the approved plan and the code currently modified in the diff.\nYou are evaluating the PROGRESS of atomic task implementation.\n\nCRITICAL RULES:\n1. Scope your audit ONLY to tasks that are marked [x] / completed in 05-tasks.md, or files present in the GIT DIFF.\n2. Ignore tasks marked [ ] / uncompleted. Do not report missing files or missing code if they belong to a future task.\n3. Identify exactly where the code in the diff diverges from the strict constraints of the Technical Contract (02-contracts.md) or the completed Task items (05-tasks.md).\n\nIf you find drift, output a short bulleted list of divergences. If the code strictly aligns with the completed plan steps, output exactly: "CONFORMANCE CHECK PASSED: Code aligns with plan."`;
    finalPrompt = `CONTRACT (02-contracts.md):\n${options?.contractText || ''}\n\nTASKS (05-tasks.md):\n${options?.tasksText || ''}\n\nGIT DIFF:\n${options?.gitDiff || ''}`;
  } else if (stageName === 'review' || stageName === 'impact') {
    systemPrompt = `You analyze code changes for subtle, distant regressions across the whole repository.\nLook for:\n1. Callers or consumers in other modules/services that relied on previous behavior or interfaces.\n2. Shared utility or package modifications that could affect unrelated services.\n3. Database query changes that affect shared tables or background workers.\n\nOutput a concise list of high-risk impact areas. Do not review code style. Focus on blast radius.`;
    finalPrompt = `GIT DIFF:\n${prompt || options?.diffText || ''}\n\nREPO SUMMARY:\n${options?.repoContext || ''}`;
  } else if (stageName === 'contract') {
    let fb = options?.feedback ? `\n\n- USER FEEDBACK & REVISION INSTRUCTIONS:\n${options.feedback}` : '';
    finalPrompt = `You are writing 02-contracts.md for a new feature.\nUse the following inputs:\n- 00-requirements.md:\n${options?.reqText || ''}\n\n- 01-recon.md:\n${options?.reconText || ''}\n\n- Template Reference:\n${options?.templateText || ''}${fb}\n\nRules:\n1. Fill every section. Where a section does not apply, write "None" and one line of justification — never delete the section.\n2. Where the recon report found no precedent, say so explicitly at the relevant point.\n3. Write plain sentences a non-engineer stakeholder could follow for every _Plain:_ prompt, then the exact technical spec below it.\n4. IMPORTANT: Do NOT use tools or ask for permissions to write files. Output the raw text of the complete 02-contracts.md markdown document directly in your response.`;
  } else if (stageName === 'merge') {
    finalPrompt = `You are plan-merger. You merge plans. You do not design.\n\nInputs:\n02-contracts.md:\n${options?.contractText || ''}\n\nDomain Plan (03-domain.md):\n${options?.layerPlans?.domain || 'None'}\n\nApp-Infra Plan (03-app-infra.md):\n${options?.layerPlans?.appInfra || 'None'}\n\nData Plan (03-data.md):\n${options?.layerPlans?.data || 'None'}\n\nSkeptic Findings (04-findings.md):\n${options?.findingsText || 'None'}\n\nRules:\n1. 02-contracts.md is immutable. Where a layer plan contradicts the contract, record it under ## Conflicts at the top of 05-tasks.md and continue.\n2. Produce a task list ordered by dependency (Schema expand -> Stored procs -> Domain types -> Ports -> Adapters -> Handlers -> Wiring -> Schema contract).\n3. Every task carries:\n   ### [ ] T-<n> <imperative title>\n   Depends on: T-<n>\n   Lane: keep | change | shared\n   Files: <paths>\n   Done when: <assertion>\n   Check: <command>\n4. Fold BLOCKER and MAJOR findings from 04-findings.md into the task it affects as an inline constraint.\n5. IMPORTANT: Do NOT use tools or ask for permissions to write files. Output the raw text of the complete 05-tasks.md markdown document directly in your response.`;
  } else if (stageName === 'coding') {
    finalPrompt = `You are implementing the atomic tasks defined in 05-tasks.md.\n\nReference Contract (02-contracts.md):\n${options?.contractText || ''}\n\nTask Specification:\n${options?.taskText || ''}\n\nInstructions:\n1. You MUST use your file editing/writing tools to implement the required code changes directly in the workspace files specified in "Files:".\n2. Follow TDD: Implement the unit/verification tests first and run the verification command ("Check:").\n3. CRITICAL: Implement EXACTLY the active task block and nothing more. DO NOT implement methods or features belonging to future tasks. If you create a class but a method is not explicitly required in this task, leave it as a \`// TODO\` to prevent diff overlap with future tasks.\n4. Do NOT just print the code in your response — you MUST write and save the changes to the disk.\n5. Verify that all changes compile, pass typechecking, and satisfy the check commands.`;
  } else if (stageName === 'code-review') {
    finalPrompt = `You are performing a final code review scoped strictly to correctness, reuse, and simplification.\n\nReview Guidelines:\n${options?.reviewRulesText || ''}\n\nGit Diff:\n${options?.diffText || prompt || ''}\n\nVerify that the code is clean, idiomatic, follows codebase conventions, and is ready to commit.\nIMPORTANT: Do NOT use tools or ask for permissions. Output the markdown review directly.`;
  }

  return { finalPrompt, systemPrompt };
}
